# Reference PDF: http://www.iptc.org/std/IIM/4.2/specification/IIMV4.2.pdf

"""
This file provides constants and clear-text names for various
well-known tags for IPTC.
"""

IPTC_IIM_TAGS = {
    # Chapter 5: Envelope Record
    "1:0": "Model Version",
    "1:5": "Destination",
    "1:20": "File Format",
    "1:22": "File Format Version",
    "1:30": "Service Identifier",
    "1:40": "Envelope Number",
    "1:50": "Product I.D.",
    "1:60": "Envelope Priority",
    "1:70": "Date Sent",
    "1:80": "Time Sent",
    "1:90": "Coded Character Set",
    "1:100": "UNO",
    "1:120": "ARM Identifier",
    "1:122": "ARM Version",
    # Chapter 6 section 1.4 Application Record No. 2
    # Record version is not human readable
    "2:0": "Record Version",
    "2:3": "Object Type Reference",
    "2:4": "Object Attribute Reference",
    "2:5": "Object Name",
    "2:7": "Edit Status",
    "2:8": "Editorial Update",
    "2:10": "Urgency",
    "2:12": "Subject Reference",
    "2:15": "Category",
    "2:20": "Supplemental Category",
    "2:22": "Fixture Identifier",
    "2:25": "Keywords",
    "2:26": "Content Location Code",
    "2:27": "Content Location Name",
    "2:30": "Release Date",
    "2:35": "Release Time",
    "2:37": "Expiration Date",
    "2:38": "Expiration Time",
    "2:40": "Special Instructions",
    "2:42": "Action Advised",
    "2:45": "Reference Service",
    "2:47": "Reference Date",
    "2:50": "Reference Number",
    "2:55": "Date Created",
    "2:60": "Time Created",
    "2:62": "Digital Creation Date",
    "2:63": "Digital Creation Time",
    "2:65": "Originating Program",
    "2:70": "Program Version",
    "2:75": "Object Cycle",
    "2:80": "By-line",
    "2:85": "By-line Title",
    "2:90": "City",
    "2:92": "Sub-location",
    "2:95": "Province/State",
    "2:100": "Country/Primary Location Code",
    "2:101": "Country/Primary Location Name",
    "2:103": "Original Transmision Reference",
    "2:105": "Headline",
    "2:110": "Credit",
    "2:115": "Source",
    "2:116": "Copyright Notice",
    "2:118": "Contact",
    "2:120": "Caption/Abstract",
    "2:122": "Writer/Editor",
    "2:125": "Rasterized Caption",
    "2:130": "Image Type",
    "2:131": "Image Orientation",
    "2:135": "Language Identifier",
    "2:150": "Audio Type",
    "2:151": "Audio Sampling Rate",
    "2:152": "Audio Sampling Resolution",
    "2:153": "Audio Duration",
    "2:154": "Audio Outcue",
    "2:200": "ObjectData Preview File Format",
    "2:201": "ObjectData Preview File Format Version",
    "2:202": "ObjectData Preview Data",
    # Chapter 11 PRE-OBJECTDATA DESCRIPTOR RECORD
    "7:10": "Size Mode",
    "7:20": "Max Subfile Size",
    "7:90": "ObjectData Size Announced",
    "7:95": "Maximum ObjectData Size",
    # Chapter 12 OBJECTDATA RECORD NUMBER 8
    "8:10": "Subfile",
    # CHAPTER 13 POST-OBJECTDATA DESCRIPTOR RECORD NUMBER 9
    "9:10": "Confirmed ObjectData Size"
}
"""Maps IPTC tags to DATASET name."""

# Dictionary to map the file format values from IIM 1:20 tag
IPTC_IIM_1X20_FILEFORMAT_TAG = {
    0: "No ObjectData",
    1: "IPTC-NAA Digital Newsphoto Parameter Record",
    2: "IPTC7901 Recommended Message Format",
    3: "Tagged Image File Format (Adobe/Aldus Image data) ",
    4: "Illustrator (Adobe Graphics data)",
    5: "AppleSingle (Apple Computer Inc)",
    6: "NAA 89-3 (ANPA 1312)",
    7: "MacBinary II",
    8: "IPTC Unstructured Character Oriented File Format (UCOFF) ",
    9: "United Press International ANPA 1312 variant",
    10: "United Press International Down-Load Message",
    11: "JPEG File Interchange (JFIF)",
    12: "Photo-CD Image-Pac (Eastman Kodak)",
    13: "Microsoft Bit Mapped Graphics File [*.BMP]",
    14: "Digital Audio File [*.WAV] (Microsoft & Creative Labs)",
    15: "Audio plus Moving Video [*.AVI] (Microsoft)",
    16: "PC DOS/Windows Executable Files [*.COM][*.EXE]",
    17: "Compressed Binary File [*.ZIP] (PKWare Inc)",
    18: "Audio Interchange File Format AIFF (Apple Computer Inc)",
    19: "RIFF Wave (Microsoft Corporation)",
    20: "Freehand (Macromedia/Aldus)",
    21: "Hypertext Markup Language HTML (The Internet Society)",
    22: "MPEG 2 Audio Layer 2 (Musicom), ISO/IEC",
    23: "MPEG 2 Audio Layer 3, ISO/IEC",
    24: "Portable Document File (*.PDF) Adobe",
    25: "News Industry Text Format (NITF)",
    26: "Tape Archive (*.TAR)",
    27: "Tidningarnas Telegrambyrå NITF version (TTNITF DTD) ",
    28: "Ritzaus Bureau NITF version (RBNITF DTD)",
    29: "Corel Draw [*.CDR]",
}
"""Maps IPTC IIM 1:20 file format name."""
